name: clang-tidy
on: [push]
jobs:
  clang-tidy-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install GLFW dependencies
        run: sudo apt-get -m install libx11-dev
        
      - uses: HorstBaerbel/action-clang-tidy@1.0
        with:
          excludedirs: 'external'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
