name: clang-tidy
on: [push]
jobs:
  clang-tidy-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: HorstBaerbel/action-clang-tidy@1.0
        with:
          excludedirs: 'external'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          style: 'file'
